# docker
steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args:
    - '-c'
    - |
      source version.sh
      docker build -t gcr.io/$PROJECT_ID/skynet-brain:$COMMIT_SHA .
      docker push gcr.io/$PROJECT_ID/skynet-brain:$COMMIT_SHA